theme = "Hydrogen"

interface = "wlp1s0"

# Lengthen uptime output
long_uptime = true

# Lengthen shell output
long_shell = true

# Lengthen kernel output
long_kernel = true

# Toggle between displaying the current shell or your user's default one.
current_shell = true

# Toggle between displaying the number of physical or logical cores of your
# processor.
physical_cores = true

show = [ "Host", "Machine", "Kernel", "Distribution",
    "OperatingSystem", "DesktopEnvironment", "WindowManager",
    "Shell", "Terminal", "Resolution", "Packages", "Processor",
    "Memory", "Battery", "Uptime"
]
