# Function key
bind = , 232, exec, brightness_control cmd --dec 10
bind = , 233, exec, brightness_control cmd --inc 10
bind = , 121, exec, amixer -D pulse sset Master 0%
bind = , 122, exec, amixer -D pulse sset Master 10%-
bind = , 123, exec, amixer -D pulse sset Master 10%+
