# Function key
binde = , 232, exec, brightness_control cmd --dec 5
binde = , 233, exec, brightness_control cmd --inc 5
bind = , 121, exec, amixer -D pulse sset Master 0%
binde = , 122, exec, amixer -D pulse sset Master 5%-
binde = , 123, exec, amixer -D pulse sset Master 5%+

# Screenshot
bind = , Print, exec, grimblast copy area
bind = SHIFT, Print, exec, grimblast save area

# Movewindow
binde = CONTROL, left, movewindow, l
binde = CONTROL, right, movewindow, r
binde = CONTROL, up, movewindow, u
binde = CONTROL, down, movewindow, d

#Resize active
binde = ALT, left, resizeactive, -20 0
binde = ALT, right, resizeactive, 20 0
binde = ALT, up, resizeactive, 0 -20
binde = ALT, down, resizeactive, 0 20
